world-time-api:
    endpoint: "http://worldtimeapi.org/api/timezone/"
    continent: "Europe"

server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: test